import type { Metadata } from "next";
import "./globals.css";
import { Recursive } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignOutButton,
  UserButton,
} from "@clerk/nextjs";

const recursive = Recursive({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Content Creator Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={recursive.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
